{
    'name': 'Bahmni Sale',
    'version': '1.0',
    'summary': 'Custom Sales module to meet bahmni requirement',
    'sequence': 1,
    'description': """
Bahmni Sale
====================
""",
    'category': 'Sales',
    'website': '',
    'images': [],
    'depends': ['base','sale', 'sale_stock','sales_team','bahmni_address_mapping','bahmni_account','point_of_sale','account'],
    'data': ['security/ir.model.access.csv',
             'security/security_groups.xml',
             'data/data.xml',
             'data/sale_config_setting.xml',
             'views/bahmni_sale.xml',
             'views/res_partner_view.xml',
             'views/village_master_view.xml',
             'views/sale_order_views.xml',
             'views/res_config_settings_view.xml',
			 'views/pos_view.xml',
             'views/address_views.xml',
             'views/custom_filters.xml',
	     'report/report_discount_heads.xml',
	     'report/sale_report.xml',
             'views/account_invoice_view.xml'],
    'demo': [],
    'qweb': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
