from . import res_partner
from . import sale_order
from . import sale_order_line
from . import res_config_settings
from . import res_company
from . import pos
from . import account_invoice
from . import shop
from . import stock_move
from . import stock_move_line
