name: Build and Publish Odoo 16
on:
  push:
    branches:
      - main
      - "release-*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**.md"
  workflow_dispatch:
jobs:
  docker-build-publish:
    name: Docker Build & Publish Odoo 16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: package/docker/odoo/Dockerfile
          push: true
          tags: bahmni/odoo-16:${{env.ARTIFACT_VERSION}},bahmni/odoo-16:latest
